[package]
name = "wecom-multi-open"
version = "0.1.0"
edition = "2021"
authors = ["open-source"]
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.54", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_Security",
    "Win32_System_WindowsProgramming",
] }

[[bin]]
name = "wecom-multi-open"
path = "src/main.rs"
