name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run tauri:build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Get version
        id: version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
          body: |
            ## 企业微信多开工具 v${{ steps.version.outputs.version }}

            ### 下载说明

            - **MSI 安装包** (推荐): 适合所有 Windows 用户
            - **NSIS 安装包**: 体积更小的安装程序

            ### 系统要求

            - Windows 10 (1809+) 或 Windows 11
            - Microsoft Edge WebView2 (通常已预装)

            ### 安装步骤

            1. 下载 MSI 或 NSIS 安装包
            2. 双击运行安装程序
            3. 按照向导完成安装
            4. 从开始菜单启动应用

            ### 使用方法

            1. 启动应用
            2. 输入要启动的实例数量 (2-5 推荐)
            3. 点击"启动多开"按钮
            4. 等待所有实例启动完成

            ### 更新内容

            请查看 [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)

            ---

            **首次使用建议启动 2-3 个实例,测试稳定性后再增加数量**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-installers
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
          retention-days: 30
